Move likes
NewSpring/Heighliner pull request #268
Opened 2017-01-19 15:40 UTC by JakeDawkins

## Questions

- I copied the mongo methods in `src/apollos/mongo` directly. They work, but I'm not sure about the `console.time` calls. Do we usually leave those in, or was that just for testing?
- If so, this should be ✅ 

## Changes

- Added filter in the userFeed resolver for likes
- Added likes model
- Added likes resolver 
- Added mutation for likes

## Tests

- likes model
- likes resolver
- likes filter in userFeed

2017-01-20 18:42 UTC, jbaxleyiii requested changes

2017-01-20 18:42 UTC, jbaxleyiii commented on src/rock/models/likes/resolver.js
> +      // XXX what should the response be if invalid/insufficient data?
@JakeDawkins we have a generic mutation response that we should implement here. https://github.com/NewSpring/Heighliner/blob/30577753b3805a1dc31dd07ef28383cfdfe94d9d/src/util/node/schema.js#L7-L11

2017-01-20 18:42 UTC, jbaxleyiii commented on src/rock/models/likes/mutations.js
> +   "toggleLike(nodeId: String!): [Node]",
This should be a `MutationResponse` that adds a `like: Node` which isn't an array. That way the client can easily update its client cache

2017-01-22 15:28 UTC, JakeDawkins commented
@jbaxleyiii whenever I try to start heighliner with these changes, I get `Error: Type "LikesMutationResponse" not found in document.` The schema is there an imported. I haven't implemented it yet in the resolver, but any ideas?

2017-01-22 16:12 UTC, jbaxleyiii commented
@JakeDawkins hmm, it should be erroring for missing resolver instead. Can you console log the schema files to make sure it is generating correctly? And maybe add the resolver for it?

2017-01-22 21:23 UTC, jbaxleyiii commented on src/rock/models/likes/model.js
> -    const existingLike = await this.model.findOne({
This should still be able to be const yes?

2017-01-22 21:23 UTC, jbaxleyiii approved these changes

2017-01-22 21:23 UTC, jbaxleyiii commented on src/rock/models/likes/model.js
> +      like: nodeModel.get(nodeId),
💯

2017-01-22 21:24 UTC, merged