added isTaxDeductable to Accounts
NewSpring/Heighliner pull request #281
Opened 2017-02-08 00:30 UTC by delianides

2017-02-08 00:48 UTC, jbaxleyiii approved these changes

2017-02-08 14:00 UTC, jbaxleyiii commented
@delianides I think this is a good change, but looking at the issue, this actually wont solve it.

The issue is with giving history both on web and in print. The methods that need adapting are:
https://github.com/NewSpring/Heighliner/blob/master/src/rock/models/finances/resolver.js#L142 and
https://github.com/NewSpring/Heighliner/blob/master/src/rock/models/finances/resolver.js#L26-L37

2017-02-08 14:01 UTC, jbaxleyiii requested changes
We need to fix the pulling of transactions, not just the pulling of accounts

2017-02-08 20:07 UTC, JakeDawkins commented on src/rock/models/finances/models/Transaction.js
> +          { model: TransactionDetail.model, where: { AccountId: { $in: deductibleAccounts } } },
@jbaxleyiii this is the only one I'm kinda unsure about, since it has multiple includes

2017-02-08 20:38 UTC, jbaxleyiii commented on src/rock/models/finances/models/Transaction.js
> +          { model: TransactionDetail.model, where: { AccountId: { $in: deductibleAccounts } } },
@JakeDawkins that should work great as you have it written

2017-02-09 13:11 UTC, jbaxleyiii approved these changes

2017-02-11 01:16 UTC, merged