Add Campus News
NewSpring/Heighliner pull request #289
Opened 2017-02-22 20:27 UTC by JakeDawkins

So far...

# Changes
- added campus to the content resolver (so we can pull campus with news)

# Tests
- added tests for resolver changes

2017-02-23 21:52 UTC, richarddubay approved these changes
YEET

2017-02-24 08:23 UTC, jbaxleyiii commented
@JakeDawkins I don't the the logged out action is worked quite right. It only returns 19 items instead of 20 which is the requested amount. We need to ensure that if the client requests 20 items, that they get back 20.

2017-02-24 08:26 UTC, jbaxleyiii requested changes

2017-02-24 08:26 UTC, jbaxleyiii commented on src/rock/models/feeds/resolver.js
> +      if (filters.includes("NEWS")) {
is this needed? We don't send a "NEWS" filter? Just "news" included in the channel list

2017-02-24 08:26 UTC, jbaxleyiii commented on src/rock/models/feeds/resolver.js
> +        // logged out only see global news
This is more a question for @jonhorton, but should a logged out user see *all* news? Or just global news? I go back and forth. @samclaridge thoughts?

2017-02-26 13:35 UTC, jonhorton commented
@jbaxleyiii I think logged out should only show global news. If you add in all of the campus entries it could get cluttered fast. + We can use the campus specific news as another reason to sign up for a NewSpring Account!

2017-02-26 14:04 UTC, JakeDawkins commented on src/rock/models/feeds/resolver.js
> +      if (filters.includes("NEWS")) {
I added this for the news section in the app. I talked with Sam and Rich, and thought the section should include all news, whereas the homefeed's is filtered by campus. Does that make sense? I couldn't think of a clean way of separating the two in the `content` filter. 

I then realized we're using the `content` query to pull news. Not the `userFeed` query. If we continue to do that, then I could remove this section.

2017-02-26 14:15 UTC, JakeDawkins commented
@jbaxleyiii regarding the query returning 19 instead of 20, that was because of how I filtered out the results. It returns the correct amount unless there's a campus specific item in the results somewhere. I could fix that by overquerying (which would break pagination, right?). 

I could also try to figure out the sequelize query to filter by campus, but that'd probably take a decent bit of time. Thoughts?

2017-02-28 18:58 UTC, richarddubay commented
@jbaxleyiii I think this looks pretty good now. You?

2017-03-02 02:18 UTC, jbaxleyiii approved these changes
@JakeDawkins excellent trip down the EE rabbit hole!

2017-03-02 02:19 UTC, merged