Add video prop to content
NewSpring/Heighliner pull request #335
Opened 2017-12-13 05:39 UTC by conrad-vanl

Adds a `video` prop to `ContentData`.

Currently returns an `embedUrl` pointing out an `html` embeddable player. We can use this to abstract the ooyala integration, but keep all of ooyala's customizations and analytics events.

If we don't care about those - I can add a `videoUrl` prop instead and potentially point to the video resource, but I might need insight on how we can generate that link.

@Lepozepo thoughts on this?

Currently a few todos in the code... need to be addressed.

2017-12-13 22:56 UTC, conrad-vanl commented
@IsaacHardy when you get an opportunity, could you look this over and let me know what you think? Basically, this gives us a spot to add video attributes on content. Right now I'm just adding an `embedUrl`, which is a url that a website or app could use to embed the player within a webview or iframe. In this case, it links to the ooyala player.

I left some comments about env vars, and a link to the existing JSON that holtzman was using to configure the player. Those env vars were actually just inside the source code on holtzman, not env vars...but I didn't know where we should put them on Heighliner for sure.  Lastly, that JSON file probably needs to be moved to an S3 endpoint, it's just important that it has CORs ability and it's served over HTTPS.

I'm working on the frontend side of this and should have a PR opened over on newspring/apollos soon.

2017-12-14 13:31 UTC, IsaacHardy commented
Hey @conrad-vanl - I'll look this through after our morning meeting around 8:30a!

2017-12-14 19:04 UTC, delianides approved these changes

2017-12-14 19:04 UTC, delianides commented on src/expression-engine/models/content/resolver.js
> +      // Todo: should these be stored as ENV vars?
these are public player codes from ooyala. you can find them now as part of the video embed.

2017-12-14 19:16 UTC, IsaacHardy commented
@conrad-vanl - The two variables are fine to stay as they are, because that bit of information is public knowledge. 

Regarding the JSON file, we are currently looking into a previous JSON file we already have up on S3.

2017-12-14 19:18 UTC, delianides commented on src/expression-engine/models/content/resolver.js
> +      const playerConfig = 'https%3A%2F%2Fdl.dropbox.com%2Fs%2Fsodcv1d9a4ezwm4%2Fskin.new.json%3Fdl%3D1';
you can use this instead
`//d3n6tjerleuu41.cloudfront.net/newspring/skin.new.json`	



config: "//d3n6tjerleuu41.cloudfront.net/newspring/skin.new.json"
52

2017-12-14 19:54 UTC, IsaacHardy requested changes
Only request is the `playerConfig` change.

2017-12-14 22:28 UTC, conrad-vanl commented
@IsaacHardy thanks for the review! I updated the player config prop to the one that @delianides  supplied.

2017-12-15 01:30 UTC, conrad-vanl commented
Was also able to fully test this locally - should be G2G! Thanks VPN!! 🙌

2017-12-18 15:14 UTC, IsaacHardy approved these changes

2017-12-18 16:46 UTC, conrad-vanl commented
@IsaacHardy thanks for the approve. FYI, we don't have push access to this repo so I can't merge myself, I think you'll have to handle any merge/deploys.

2017-12-18 17:21 UTC, IsaacHardy commented
@conrad-vanl We are trying to determine the best means for merging in y'alls changes to master. We are trying to figure out a good way to handle simaltansion development from Differential and NewSpring. Any ideas are also welcomed!

Once we figure out a plan of action, we will proceed with the merge. 

Are y'all in dire need of these changes to be merged into the master branch?

2017-12-19 02:22 UTC, conrad-vanl commented
> Are y'all in dire need of these changes to be merged into the master branch?

Nope! All is good for now.

> Any ideas are also welcomed!

We can talk about it on standup this week (or sooner if you'd like)

2017-12-20 23:30 UTC, merged